global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "api"
    static_configs:
      - targets: ["api-service:8000"]
  
  - job_name: "database"
    static_configs:
      - targets: ["db-service:5432"]

  - job_name: "tracing"
    static_configs:
      - targets: ["tempo:3100"]
